#!/usr/bin/env python3
"""Worn office-badge props, CR80 (2.125 x 3.375in), printed portrait.

Four badges: two per PC, a current one and a dead one. Fronts on sheet 1, backs
on sheet 2, **column order reversed on the back** so a long-edge duplex lands
each back behind its own front.

The backs are deliberately timid: every mark sits inside a 0.30in safe margin,
there is no bleed and no edge art, so a cut that wanders by an eighth of an inch
still produces a badge that looks right.

Portraits are generated by badge_photo.py — no stock library and no real person.
Names are read from characters/pcs/*.json.

    ./make-badges.py --out badges.pdf
"""
import argparse, base64, io, json, pathlib, shutil, subprocess, sys, tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import badge_photo

ap = argparse.ArgumentParser()
ap.add_argument("--out", type=pathlib.Path, default=HERE / "badges.pdf")
ap.add_argument("--keep-html", action="store_true")
args = ap.parse_args()

PCS = HERE.parent / "characters" / "pcs"
name = lambda slug: json.loads((PCS / f"{slug}.json").read_text())["name"]
MIRA, MORGAN = name("mira-sun"), name("morgan-reyes")


def photo(seed, palette, severity):
    im = badge_photo.make(seed, palette, severity, size=(300, 380))
    buf = io.BytesIO(); im.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


BADGES = [
    dict(accent="#1c4f7c", org="County of San Mateo",
         sub="Assessor &middot; County Clerk &middot; Recorder",
         holder=MIRA, title="Clerk II &mdash; Recorder's Office",
         no="SMC&nbsp;04-22871", issued="ISSUED 08/2025", expires="EXP 08/2028",
         band="EMPLOYEE", state="", photo=photo("smc", "a", 0.70),
         foot="Redwood City &middot; 555 County Center",
         backline="Property of the County of San Mateo. If found, drop in any mailbox."),
    dict(accent="#6b1d2e", org="San Francisco State University",
         sub="OneCard &middot; Graduate Division",
         holder=MIRA, title="Graduate Student &mdash; Linguistics (MA, deferred)",
         no="SFSU&nbsp;918-446-03", issued="ISSUED 08/2023", expires="EXP 05/2025",
         band="STUDENT", state="EXPIRED", photo=photo("sfsu", "b", 0.86),
         foot="1600 Holloway Avenue",
         backline="Non-transferable. Return to the OneCard office, Student Services."),
    dict(accent="#2f4038", org="Meridian Logic Systems",
         sub="Federal Facility Credential",
         holder=MORGAN, title="Contractor &mdash; Assessment Team",
         no="MLS&nbsp;C-7734", issued="ISSUED 03/2021", expires="EXP 03/2024",
         band="ESCORT REQUIRED", state="VOID", photo=photo("mls", "c", 0.92),
         foot="Credential remains U.S. Government property",
         backline="Surrender on separation. Report loss within 24 hours."),
    dict(accent="#7a5a12", org="Vo &amp; Associates",
         sub="Corporate Investigations &middot; Oakland",
         holder=MORGAN, title="Investigator &mdash; Records",
         no="V&amp;A&nbsp;011", issued="ISSUED 02/2027", expires="EXP 02/2029",
         band="STAFF", state="", photo=photo("mls", "c", 0.92),
         foot="2140 Grand Avenue, Oakland",
         backline="Licensed under CA BSIS. Not a peace officer credential."),
]

CSS = """
@page { size: letter; margin: 0.55in; }
* { box-sizing: border-box; }
body { margin:0; font-family:"Helvetica Neue",Arial,sans-serif; color:#1d1b17;
       -webkit-print-color-adjust:exact; print-color-adjust:exact; }
h1 { font-size:10pt; letter-spacing:.16em; text-transform:uppercase;
     margin:0 0 8px; color:#6b6250; font-weight:700; }
.note { font-size:7.6pt; color:#6b6250; margin:0; line-height:1.4; }
/* Fixed-height header on BOTH sheets: the two grids must start at the
   identical y or the duplex registration is off before the cut begins. */
.head { height:0.86in; overflow:hidden; }
.grid { display:grid; grid-template-columns:2.125in 2.125in; gap:0.60in 1.00in;
        justify-content:center; }
.slot { position:relative; }
.badge { width:2.125in; height:3.375in; position:relative; overflow:hidden;
         border:0.5pt solid #b9b2a2; border-radius:0.09in; background:#fbfaf7; }
.crop { position:absolute; width:0.16in; height:0.16in; border:0.4pt solid #9a9488; }
.c1 { left:-0.11in; top:-0.11in; border-right:none; border-bottom:none; }
.c2 { right:-0.11in; top:-0.11in; border-left:none; border-bottom:none; }
.c3 { left:-0.11in; bottom:-0.11in; border-right:none; border-top:none; }
.c4 { right:-0.11in; bottom:-0.11in; border-left:none; border-top:none; }

.hdr { padding:0.24in 0.10in 0.06in; text-align:center; color:#fff; }
.org { font-size:7.4pt; font-weight:700; letter-spacing:.05em; line-height:1.15; }
.sub { font-size:5.4pt; letter-spacing:.10em; text-transform:uppercase;
       opacity:.86; margin-top:2px; }
.slotcut { position:absolute; top:0.09in; left:50%; transform:translateX(-50%);
           width:0.46in; height:0.095in; border:0.5pt solid rgba(255,255,255,.55);
           border-radius:0.05in; }
.pho { width:1.02in; height:1.29in; margin:0.09in auto 0.05in; display:block;
       border:0.5pt solid rgba(0,0,0,.28); object-fit:cover; }
.nm { text-align:center; font-size:9.6pt; font-weight:700; margin:0 0.06in;
      line-height:1.1; }
.ti { text-align:center; font-size:5.9pt; color:#4a4438; margin:2px 0.09in 0;
      line-height:1.25; }
.band { margin:0.07in 0.09in 0; text-align:center; font-size:5.6pt; font-weight:700;
        letter-spacing:.16em; padding:2px 0; color:#fff; }
.meta { position:absolute; left:0.09in; right:0.09in; bottom:0.21in;
        font-size:5.2pt; color:#57503f; letter-spacing:.04em; }
.meta div { display:flex; justify-content:space-between; margin-top:1px; }
.no { font-weight:700; letter-spacing:.06em; font-size:5.8pt; }
.bars { position:absolute; left:0.09in; right:0.09in; bottom:0.075in; height:0.10in;
        background:repeating-linear-gradient(90deg,#211f1b 0 0.8pt,transparent .8pt 1.9pt,
        #211f1b 1.9pt 3.4pt,transparent 3.4pt 4.6pt,#211f1b 4.6pt 5.4pt,transparent 5.4pt 7.2pt);
        opacity:.70; }
.stamp { position:absolute; top:47%; left:50%; font-size:18pt; font-weight:800;
         letter-spacing:.14em; color:rgba(150,26,26,.40);
         border:2.6pt solid rgba(150,26,26,.34); padding:1px 8px; border-radius:2px;
         transform:translate(-50%,-50%) rotate(-14deg); white-space:nowrap; }
.wear { position:absolute; inset:0; pointer-events:none;
        background:
          radial-gradient(120% 60% at 50% -10%, rgba(255,255,255,.28), transparent 60%),
          radial-gradient(80% 50% at 108% 62%, rgba(120,105,80,.16), transparent 62%),
          radial-gradient(70% 45% at -8% 88%, rgba(120,105,80,.14), transparent 62%),
          linear-gradient(103deg, transparent 46%, rgba(255,255,255,.20) 48%, transparent 51%),
          linear-gradient(88deg, transparent 71%, rgba(90,80,60,.10) 72.5%, transparent 74%); }

.back { background:#f4f2ec; }
.safe { position:absolute; inset:0.30in; display:flex; flex-direction:column; }
.mag { height:0.34in; background:#2a2622; margin-bottom:0.14in; }
.bk-org { font-size:6.6pt; font-weight:700; letter-spacing:.06em; line-height:1.2; }
.bk-holder { font-size:5.8pt; color:#4a4438; margin-top:2px; letter-spacing:.03em; }
.bk-line { font-size:5.6pt; color:#4a4438; line-height:1.45; margin-top:0.06in; }
.bk-no { font-size:5.8pt; font-weight:700; letter-spacing:.06em; margin-top:0.10in; }
.sig { margin-top:auto; border-top:0.5pt solid #8d8676; padding-top:2px;
       font-size:4.8pt; letter-spacing:.10em; color:#6b6250; }
.prop { font-size:4.4pt; color:#8d8676; letter-spacing:.06em; margin-top:0.05in; }
"""

CROPS = ('<div class="crop c1"></div><div class="crop c2"></div>'
         '<div class="crop c3"></div><div class="crop c4"></div>')


def front(b):
    stamp = f'<div class="stamp">{b["state"]}</div>' if b["state"] else ""
    return f"""<div class="slot">{CROPS}<div class="badge">
  <div class="hdr" style="background:{b['accent']}">
    <div class="slotcut"></div>
    <div class="org">{b['org']}</div><div class="sub">{b['sub']}</div>
  </div>
  <img class="pho" src="{b['photo']}" alt="">
  <div class="nm">{b['holder']}</div>
  <div class="ti">{b['title']}</div>
  <div class="band" style="background:{b['accent']}">{b['band']}</div>
  <div class="meta">
    <div><span class="no">{b['no']}</span></div>
    <div><span>{b['issued']}</span><span>{b['expires']}</span></div>
    <div><span>{b['foot']}</span></div>
  </div>
  <div class="bars"></div>{stamp}<div class="wear"></div>
</div></div>"""


def back(b):
    return f"""<div class="slot">{CROPS}<div class="badge back">
  <div class="safe">
    <div class="mag"></div>
    <div class="bk-org">{b['org']}</div>
    <div class="bk-holder">{b['holder']}</div>
    <div class="bk-line">{b['backline']}</div>
    <div class="bk-no">{b['no']}</div>
    <div class="sig">SIGNATURE</div>
    <div class="prop">PROP &middot; NOT A GENUINE CREDENTIAL</div>
  </div>
</div></div>"""


rows = [BADGES[0:2], BADGES[2:4]]
back_order = [b for r in rows for b in reversed(r)]

HTML = f"""<meta charset="utf-8"><title>Badges</title><style>{CSS}</style>
<div class="head"><h1>Badges &mdash; fronts</h1>
<p class="note"><b>Print double-sided, flip on the LONG edge, at 100% scale
&mdash; not &ldquo;fit to page&rdquo;, which would change the card size.</b>
Cut on the badge outline; the corner marks are guides and get cut away.
<b>Every mark on the back sits 0.30in inside the edge</b>, so a cut that wanders
costs you nothing.</p></div>
<div class="grid">{''.join(front(b) for b in BADGES)}</div>
<div style="page-break-before:always"></div>
<div class="head"><h1>Badges &mdash; backs</h1>
<p class="note">Mirrored left-to-right to match the fronts on a long-edge flip.
If your printer flips on the short edge instead, rotate this sheet 180&deg;
before the second pass.</p></div>
<div class="grid">{''.join(back(b) for b in back_order)}</div>
"""

out_pdf = args.out.resolve()
out_html = (out_pdf.with_suffix(".html") if args.keep_html
            else pathlib.Path(tempfile.mkdtemp(prefix="badges-")) / "badges.html")
out_html.write_text(HTML)
chrome = next((c for c in ("google-chrome", "chromium", "chromium-browser",
                           "google-chrome-stable") if shutil.which(c)), None)
if chrome is None:
    sys.exit("no Chrome/Chromium on PATH")
subprocess.run([chrome, "--headless", "--disable-gpu", "--no-sandbox",
                "--no-pdf-header-footer", f"--print-to-pdf={out_pdf}",
                f"file://{out_html}"], check=True, capture_output=True)
print(f"Wrote {out_pdf} ({out_pdf.stat().st_size//1024} KB) — {len(BADGES)} badges")
